# -----------------------------------------------------
# Window rules
# -----------------------------------------------------

# idleinhibit
# windowrule = match:class = ([window]), idleinhibit = fullscreen # Available modes: none, always, focus, fullscreen

#xwayland related rules
# when moving objects in resolve a large border is produced 
# This rule prevents that and serves as a template for any problematic xwayland apps
# windowrule = noblur, class:^(\bresolve\b)$, xwayland:1
# This is a general rule for xwayland apps but can have other consequences 
# for one user it impacted EMACs so it's disabled by default 
# It's here as a reference or for quick triage of xwayland ap
#windowrule = noblur, xwayland:1


# flotar cualquier ventana modal
windowrule {
  name = float-modals
  match:modal = true
  float = on
  center = on
}

windowrule = match:class xdg-desktop-portal-gtk, float true, center true, size 1200 700

windowrule = match:title (Open File|Confirm|Error|Warning|Settings|Preferences|Guardar como|Abrir|Confirmar), float true, center true

windowrule = match:class nemo, match:title .*(Properties|Propiedades).*, float true, center true, size 800 600

