cursor #e8e0e5
cursor_text_color #cfc3cd

# foreground            #e8e0e5
# background            #151215
# selection_foreground  #3a2b3d

foreground              #cdd6f4
background              #1e1e2e
selection_foreground    #1e1e2e


selection_background  #d6c0d6
url_color             #f1afff

# black
color8   #e8e0e5
color0   #4c4c4c

# red
color1   #ffb4ab
color9   #c49ea0

# green
color2   #f1afff
color10  #9ec49f

# yellow
color3   #aca98a
color11  #c4c19e

# blue
color4  #f1afff
color12 #a39ec4

# magenta
color5   #ffb4ab
color13  #c49ec4

# cyan
color6   #e8e0e5
color14  #9ec3c4

# white
color15   #e7e7e7
color7  #f0f0f0
