-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    decoration = {
        inactive_opacity = 0.95,
    },
    ecosystem = {
        no_donation_nag = true,
    },
    general = {
        border_size = 3,
        gaps_out = 20,
    },
    gestures = {
        workspace_swipe_create_new = true,
    },
    input = {
        kb_options = "caps:swapescape",
    },
    misc = {
        focus_on_activate = true,
    },
})
