#!/bin/bash
SOCKET="/tmp/nvimsocket"
# Definimos la clase para que sea siempre nvim-term
CLASS="nvim-term"

if [ -S "$SOCKET" ]; then
  # Si ya existe, enviamos el comando a la instancia existente.
  # Usamos --remote-send para evitar que abra una ventana nueva de kitty.
  nvim --server "$SOCKET" --remote-send "<C-\><C-n>:tabedit $1<CR>"
  # Opcional: Esto fuerza el foco a la ventana si tienes herramientas de compositor
  hyprctl dispatch focuswindow class:$CLASS
else
  # Si es la primera vez, lanzamos kitty con la clase nvim-term
  kitty --class "$CLASS" -e nvim --listen "$SOCKET" "$@"
fi
