[[mgr.prepend_keymap]]
on = ["g", "m"]
run = "cd ~/.mydotfiles/com.ml4w.dotfiles/.config"
desc = "Go ML4W Config"

[[mgr.prepend_keymap]]
on = ["g", "D"]
run = "cd ~/Documentos"
desc = "Go ~/Documentos/"

[[mgr.prepend_keymap]]
on = ["g", "d"]
run = "cd ~/Descargas/"
desc = "Go ~/Descargas/"

[[mgr.prepend_keymap]]
on = ["g", "h"]
run = "cd ~"
desc = "Go ~"

[[mgr.prepend_keymap]]
on = ["g", "H"]
run = "cd ~/.mydotfiles/com.ml4w.dotfiles.stable/.config/hypr/"
desc = "Go Hypr Config"

[[mgr.prepend_keymap]]
on = ["g", "."]
run = ["cd /home/abraham/MisDotfiles", "hidden toggle" ]
desc = "Go MisDotfiles"

[[mgr.prepend_keymap]]
on = ["z", "u"]
run = "shell -- ouch decompress %s"
desc = "Descomprimir archivos seleccionados"

[[mgr.prepend_keymap]]
on = ["z", "z"]
run = "shell -- ouch compress %s %h.zip"
desc = "Comprimir selección en .zip"

[[mgr.prepend_keymap]]
on = ["z", "t"]
run = "shell -- ouch compress %s %h.tar.gz"
desc = "Comprimir selección en .tar.gz"

[[mgr.prepend_keymap]]
on = ["z", "7"]
run = "shell -- ouch compress %s %h.7z"
desc = "Comprimir selección en .7z"

[[mgr.prepend_keymap]]
on = ["e", "a"]
run = "shell -- chmod +x %h"
desc = "Dar permiso de ejecución (+x)"

[[mgr.prepend_keymap]]
on = ["e", "r"]
run = "shell -- chmod -x %h"
desc = "Quitar permiso de ejecución (-x)"

[[mgr.prepend_keymap]]
on = "H"
run = "tab_switch -1 --relative"
desc = "Cambiar a la pestaña anterior"

[[mgr.prepend_keymap]]
on = "L"
run = "tab_switch 1 --relative"
desc = "Cambiar a la siguiente pestaña"

[[mgr.prepend_keymap]]
on = "i"
run = "plugin zoxide"
desc = "Buscar carpetas con Zoxide"

[[mgr.prepend_keymap]]
on = "I"
run = "plugin fzf"
desc = "Buscar archivos con fzf"

[[mgr.prepend_keymap]]
on = "M"
run = "plugin mount"

# m -> Mount the partition
# u -> Unmount the partition
# e -> Eject the disk

[[mgr.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "Chmod on selected files"
#
# [[mgr.prepend_keymap]]
# on = "+"
# run = "plugin zoom 1"
# desc = "Zoom in hovered file"
#
# [[mgr.prepend_keymap]]
# on = "-"
# run = "plugin zoom -1"
# desc = "Zoom out hovered file"
#
[[mgr.prepend_keymap]]
on = "f"
run = "plugin smart-filter"
desc = "Smart filter"

[[mgr.prepend_keymap]]
on = "F"
run = "filter --smart"
desc = "Smart filter"

# sudo cp/mv
[[mgr.prepend_keymap]]
on = ["R", "p"]
run = "plugin sudo -- paste"
desc = "sudo paste"

# sudo cp/mv --force
[[mgr.prepend_keymap]]
on = ["R", "P"]
run = "plugin sudo -- paste --force"
desc = "sudo paste force"

# sudo mv
[[mgr.prepend_keymap]]
on = ["R", "r"]
run = "plugin sudo -- rename"
desc = "sudo rename"

# sudo ln -s (absolute-path)
[[mgr.prepend_keymap]]
on = ["R", "l", "l"]
run = "plugin sudo -- link"
desc = "sudo link"

# sudo ln -s (relative-path)
[[mgr.prepend_keymap]]
on = ["R", "p", "r"]
run = "plugin sudo -- link --relative"
desc = "sudo link relative path"

# sudo ln
[[mgr.prepend_keymap]]
on = ["R", "l", "L"]
run = "plugin sudo -- hardlink"
desc = "sudo hardlink"

# sudo touch/mkdir
[[mgr.prepend_keymap]]
on = ["R", "a"]
run = "plugin sudo -- create"
desc = "sudo create"

# sudo trash
[[mgr.prepend_keymap]]
on = ["R", "d"]
run = "plugin sudo -- remove"
desc = "sudo trash"

# sudo delete
[[mgr.prepend_keymap]]
on = ["R", "D"]
run = "plugin sudo -- remove --permanently"
desc = "sudo delete"

# sudo chmod
[[mgr.prepend_keymap]]
on = ["R", "m"]
run = "plugin sudo -- chmod"
desc = "sudo chmod"

[[mgr.prepend_keymap]]
on = ["u", "u"]
run = "plugin restore"
desc = "Restore last deleted files/folders"

# # This will throw error when there is existed file/folder
# [[mgr.prepend_keymap]]
# on = ["u", "i"]
# run = "plugin restore -- --interactive"
# desc = "Restore deleted files/folders (Interactive)"

    # Select files/folders to restore. Input item index or range separated by comma:
    # - Restore a trashed file:
    #      What file to restore [0..4]: 4
    # - Restore multiple trashed files separated by comma, also support range:
    #      What file to restore [0..3]: 0-2, 3

# [[mgr.prepend_keymap]]
# on = ["U", "o"]
# run = "plugin restore -- --interactive --interactive-overwrite"
# desc = "Restore deleted files/folders (Interactive overwrite)"

[[mgr.prepend_keymap]]
on = [ "t", "R" ]
run = "plugin close-and-restore-tab restore"
desc = "Restore the previously closed tab"

[[mgr.prepend_keymap]]
on = [ "T" ]
run = "plugin close-and-restore-tab restore"
desc = "Restore the previously closed tab"

[[mgr.prepend_keymap]]
on   = [ "Z", "a", "a" ]
run  = "plugin compress"
desc = "Archive selected files"

[[mgr.prepend_keymap]]
on   = [ "Z", "a", "p" ]
run  = "plugin compress -p"
desc = "Archive selected files (password)"

[[mgr.prepend_keymap]]
on   = [ "Z", "a", "h" ]
run  = "plugin compress -ph"
desc = "Archive selected files (password+header)"

[[mgr.prepend_keymap]]
on   = [ "Z", "a", "l" ]
run  = "plugin compress -l"
desc = "Archive selected files (compression level)"

[[mgr.prepend_keymap]]
on   = [ "Z", "a", "u" ]
run  = "plugin compress -phl"
desc = "Archive selected files (password+header+level)"

[[mgr.prepend_keymap]]
on = ["C", "p"]
run = "plugin convert -- --extension='png'"
desc = "Convert selected files to PNG"

[[mgr.prepend_keymap]]
on = ["C", "j"]
run = "plugin convert -- --extension='jpg'"
desc = "Convert selected files to JPG"

[[mgr.prepend_keymap]]
on = ["C", "w"]
run = "plugin convert -- --extension='webp'"
desc = "Convert selected files to WebP"

[[mgr.prepend_keymap]]
on   = [ "<C-D>" ]
run  = "plugin drag"
desc = "Drag Files"

[[mgr.prepend_keymap]]
on = [ "1" ]
run = "plugin relative-motions 1"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "2" ]
run = "plugin relative-motions 2"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "3" ]
run = "plugin relative-motions 3"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "4" ]
run = "plugin relative-motions 4"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "5" ]
run = "plugin relative-motions 5"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "6" ]
run = "plugin relative-motions 6"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "7" ]
run = "plugin relative-motions 7"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "8" ]
run = "plugin relative-motions 8"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "9" ]
run = "plugin relative-motions 9"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "u", "b" ]
run = "plugin recycle-bin"
desc = "Open recicle bin menu"

[[mgr.prepend_keymap]]
on = [ "<C-p>" ]
run = "paste --force"
desc = "Paste yanked files (overwrite if file exists in the destinatio)"

[[mgr.prepend_keymap]]
on = [ "P", "s" ]
run = "plugin projects save"
desc = "Save current project"

[[mgr.prepend_keymap]]
on = [ "P", "L" ]
run = "plugin projects load"
desc = "Load project"

[[mgr.prepend_keymap]]
on = [ "P", "l" ]
run = "plugin projects load_last"
desc = "Load last project"

[[mgr.prepend_keymap]]
on = [ "P", "d" ]
run = "plugin projects delete"
desc = "Delete project"

[[mgr.prepend_keymap]]
on = [ "P", "D" ]
run = "plugin projects delete_all"
desc = "Delete all projects"

[[mgr.prepend_keymap]]
on = [ "P", "m" ]
run = "plugin projects 'merge current'"
desc = "Merge current tab to other projects"

[[mgr.prepend_keymap]]
on = [ "P", "M" ]
run = "plugin projects 'merge all'"
desc = "Merge current project to other projects"

[[mgr.prepend_keymap]]
on = [ "p" ]
run = "plugin ucp paste"
desc = "Paste"

[[mgr.prepend_keymap]]
on = [ "y" ]
run = "plugin ucp copy"
desc = "Copy"
