# Matugen template for btop

# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#1e1e2e"

# Main text color
theme[main_fg]="#e3e2e6"

# Title color for boxes
theme[title]="#a9c8ff"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#bdc7dc"

# Background color of selected item in processes box 
theme[selected_bg]="#dcbce1"

# Foreground color of selected item in processes box 
theme[selected_fg]="#1e1e2e"

# Color of inactive/disabled text
theme[inactive_fg]="#c4c6cf"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#dcbce1"

# Cpu box outline color
theme[cpu_box]="#8e9099"

# Memory/disks box outline color
theme[mem_box]="#8e9099"

# Net up/down box outline color
theme[net_box]="#8e9099"

# Processes box outline color
theme[proc_box]="#8e9099"

# Box divider line and small boxes line color
theme[div_line]="#43474e"

# Temperature graph colors
theme[temp_start]="#bdc7dc"
theme[temp_mid]="#a9c8ff"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#a9c8ff"
theme[cpu_mid]="#a9c8ff"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#bdc7dc"
theme[free_mid]=""
theme[free_end]="#3e4758"

# Mem/Disk cached meter
theme[cached_start]="#dcbce1"
theme[cached_mid]=""
theme[cached_end]="#563e5c"

# Mem/Disk available meter
theme[available_start]="#a9c8ff"
theme[available_mid]=""
theme[available_end]="#00468b"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#bdc7dc"
theme[download_mid]="#a9c8ff"
theme[download_end]="#dcbce1"

# Upload graph colors
theme[upload_start]="#bdc7dc"
theme[upload_mid]="#a9c8ff"
theme[upload_end]="#dcbce1"
